### ISSUE TITLE
[QUESTION] DAIDALUS configuration change

### ISSUE THREAD

**Issue by aadeabreu** [mit-ll/degas-daidalus#1]
@cserres We have added `daa.loadFromFile('filename.conf');` to DaidalusAlertAndGuidance.ccp at line 108 right after `daa.set_Buffered_WC_DO_365(true);` and mex the function again. 

The goal is to be able to change between configuration files located in `nasa/daidalus/Configurations/`. Do you see any drawbacks to using `daa.loadFromFile()`? Other than not being able to change configuration quickly if the filename is hardcoded. We are still using the alerters defined through DaidalusV201.m.

**Comment by bgill92** [comment]
@aadeabreu  If you want to use all of the configuration parameters from a configuration file, I would recommend putting `daa.loadFromFile('filename.conf');` after line 142. I believe all of alerter parameters (the WCVTables), alerters, and other options (from lines 137 to 142) are read in from the configuration file and configured using `daa.loadFromFile()`. I am assuming that you are using one of the configuration files listed here https://github.com/nasa/daidalus/tree/DAIDALUSv2.0.1c/Configurations. Hopefully that works, but let us know if you aren't seeing expected behavior.

**Comment by aadeabreu** [comment]
@bgill92 Perfect, thank you. I do see the expected behavior and just wanted to confirm that it would not create any conflicts.
